### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by cedricve** [jonahbron/angular-owl-carousel#21]
Downloaded and tested software as is, however throws an error.

`angular.js:14110 SyntaxError: [verstraetenIo Error] Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.link (http://10.10.10.10:3000/bower_components/angular-owl-carousel/src/angular-owl-carousel.js:18:36)
    at http://10.10.10.10:3000/bower_components/angular/angular.js:1259:18
    at invokeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:10095:9)
    at nodeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:9492:11)
    at compositeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:8757:13)
    at compositeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:8760:13)
    at compositeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:8760:13)
    at compositeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:8760:13)
    at nodeLinkFn (http://10.10.10.10:3000/bower_components/angular/angular.js:9486:11) <div owl-carousel="vm.owl.items" owl-options="vm.owl.options">(anonymous function) @ angular.js:14110(anonymous function) @ angular.js:10633(anonymous function) @ exception-handler.provider.js:55invokeLinkFn @ angular.js:10097nodeLinkFn @ angular.js:9492compositeLinkFn @ angular.js:8757compositeLinkFn @ angular.js:8760compositeLinkFn @ angular.js:8760compositeLinkFn @ angular.js:8760nodeLinkFn @ angular.js:9486compositeLinkFn @ angular.js:8757publicLinkFn @ angular.js:8637(anonymous function) @ angular-ui-router.js:4089(anonymous function) @ angular.js:1259invokeLinkFn @ angular.js:10095nodeLinkFn @ angular.js:9492compositeLinkFn @ angular.js:8757publicLinkFn @ angular.js:8637lazyCompilation @ angular.js:8994updateView @ angular-ui-router.js:4021(anonymous function) @ angular-ui-router.js:3959$broadcast @ angular.js:18239$state.transition.resolved.then.$state.transition @ angular-ui-router.js:3352processQueue @ angular.js:16606(anonymous function) @ angular.js:16622$eval @ angular.js:17913$digest @ angular.js:17727$apply @ angular.js:18021done @ angular.js:12002completeRequest @ angular.js:12211requestLoaded @ angular.js:12139
angular.js:14110 Error: [verstraetenIo Error] Unexpected token v in JSON at position 0 Object {exception: SyntaxError: [verstraetenIo Error] Unexpected token v in JSON at position 0
    at JSON.parse (<anon…, cause: "<div owl-carousel="vm.owl.items" owl-options="vm.owl.options">"}`

**Comment by ddtch** [comment]
I have same issue. Is it occurs when using `Controller as vm` syntax?

**Comment by emalikterzi** [comment]
@ddtch hi , you can use mine :) https://github.com/emalikterzi/angular-owl-carousel-2

**Comment by RonAlmog** [comment]
same problem here.  Unexpected token v in JSON at position 0.
this is where it is trying to read the vm.owl.options and json parse it.  Any advice?
data copied from the sample:
vm.owl = {
        items: ['item 1', 'item 2'],
        options: {
            loop: true,
            nav: false
        }
      };

**Comment by jonahbron** [comment]
It used to require JSON in the directive attribute, but @rickerd improved the interface.  I just created a new release based on his changes, check it out.

https://github.com/jonahbron/angular-owl-carousel/releases/tag/v0.3.0

**Comment by RonAlmog** [comment]
still not working.
TypeError: $element.owlCarousel is not a function
    at angular-owl-carousel.js:122

using owl-carousel 2.  any advice?
maybe clarify the way to add the owl-carousel to the project? maybe we're doing it wrong.
again, a working example would be very helpful ;)

**Comment by dashawk** [comment]
This #24 should fix the problem

**Comment by dashawk** [comment]
If this is still not fixed, you can try my version of [angularOwlCarousel](https://github.com/dashawk/angularOwlCarousel).
